### ISSUE TITLE
Fix expected failling test with unknown tilde syntax

### ISSUE THREAD

**Issue by agjohnson** [rtfd/sphinxcontrib-dotnetdomain#12]
An unknown syntax involving a tilde after the definition, ie:
```
Microsoft.CodeAnalysis.Options.Option`1.op_Implicit(Microsoft.CodeAnalysis.Options.Option{`0})~Microsoft.CodeAnalysis.Options.OptionKey
```

Failing test here:
https://github.com/rtfd/sphinxcontrib-dotnetdomain/blob/083dccdf42b2f960f41770e57e34f1cf668df2de/tests/test_signature.py#L102-L113

**Comment by danroth27** [comment]
For conversion operators only (op_Implicit and op_Explicit), the return value of the method is encoded as a '~' followed by the return type. See https://msdn.microsoft.com/en-us/library/vstudio/fsbx0t7x(v=vs.140).aspx.
