### ISSUE TITLE
Autodoc capabilities

### ISSUE THREAD

**Issue by lionpeloux** [rtfd/sphinxcontrib-dotnetdomain#39]
Thank you for this domain which looks promising and very helpful.

I'm trying to document a C# project with sphinx and RTD.
So far, I've been able to install this domain and build a test doc looking at `syntax.rst.

I understand this domain is still in development, but would you mind giving few informations about the capabilities ?

* is there any autodoc capabilities to scan C# XML doc ?
* is there any autodoc capabilities to auto generate class and method signatures ?
* is there any tag for method parameter ?
* is there tag for method return ?
* is there any tag for ref/out keyword ?

Thank you for helping,
Lionel

**Comment by agjohnson** [comment]
Autodoc is not part of Sphinx domains, we are building some of that, relying on the `docfx` tool, in rtfd/sphinx-autoapi.

Here's an example that shows a method definition in rST, parameter and return definitions, and a ref link:

```rst
.. dn:method:: Foo.method(FooType bar)
   :param bar: A Bar instance
   :type bar: :dn:cls:`Bar`
   :returns: Altered bar instance

   On :dn:cls:`Foo` instance, return :dn:cls:`Bar` instance
```

**Comment by lionpeloux** [comment]
Thank you for your kind answer and your example.

Indeed, I've been looking to the autoapi, trying to make it work but I'm still missing something.
Hopefully, I'll get some valuable help from [here](https://github.com/rtfd/sphinx-autoapi/issues/41#issuecomment-151912315) and make it work.

Thanks again.
Lionel
