### ISSUE TITLE
Type and member formatting changes depending on presence of documentation

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinxcontrib-dotnetdomain#45]
The formatting of a type or member changes pretty dramatically depending on the presence of documentation.

With documentation:
![image](https://cloud.githubusercontent.com/assets/1874516/11847847/417f6d68-a3d4-11e5-9896-763be420ab89.png)

Without documentation:
![image](https://cloud.githubusercontent.com/assets/1874516/11847860/4b8ee914-a3d4-11e5-8168-a839f161f130.png)

Is there a way to make the formatting consistent?

**Comment by agjohnson** [comment]
This looks to be dependent on the rST autoapi output, moving the issue there
